----------------------------------------------------------------------------------
-- Testbench: hann_window_4096_tb
--
-- Description:
--   Self-checking simulation for the Hann window IP. The coefficient ROM is
--   loaded from hann_window.mem, and expected 24-bit windowed samples are loaded from
--   hann_window_4096_tb_expected.mem. Both files are generated by
--   tools/generate_hann_window.py so the testbench checks against the same
--   fixed-point truncation model used to create the ROM contents.
----------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
use ieee.std_logic_textio.all;
use std.env.all;

entity hann_window_4096_tb is
end entity hann_window_4096_tb;

architecture sim of hann_window_4096_tb is

    constant CLK_PERIOD  : time := 10 ns;
    constant TEST_COUNT  : natural := 5;
    constant INDEX_WIDTH : natural := 12;
    constant SAMPLE_W    : natural := 24;

    type index_array_t is array (0 to TEST_COUNT - 1) of unsigned(INDEX_WIDTH - 1 downto 0);
    type sample_array_t is array (0 to TEST_COUNT - 1) of signed(SAMPLE_W - 1 downto 0);
    type output_array_t is array (0 to TEST_COUNT - 1) of signed(SAMPLE_W - 1 downto 0);

    --------------------------------------------------------------------------
    -- Input vectors.
    --
    -- These indices exercise both zero-valued window endpoints, near-center
    -- full-amplitude coefficients, positive input samples, and negative input
    -- samples. The expected 24-bit truncated outputs for these exact vectors
    -- are generated by Python and loaded below.
    --------------------------------------------------------------------------
    constant TEST_INDEXES : index_array_t := (
        to_unsigned(0, INDEX_WIDTH),
        to_unsigned(1, INDEX_WIDTH),
        to_unsigned(2047, INDEX_WIDTH),
        to_unsigned(2048, INDEX_WIDTH),
        to_unsigned(4095, INDEX_WIDTH)
    );

    constant TEST_SAMPLES : sample_array_t := (
        to_signed(1000000, SAMPLE_W),
        to_signed(683183, SAMPLE_W),
        to_signed(8388607, SAMPLE_W),
        to_signed(-8388608, SAMPLE_W),
        to_signed(-1234567, SAMPLE_W)
    );

    --------------------------------------------------------------------------
    -- Expected output loader.
    --
    -- The expected file contains one signed 24-bit two's-complement output per
    -- line. Loading these values avoids duplicating the Hann fixed-point math by
    -- hand in the testbench.
    --------------------------------------------------------------------------
    impure function load_expected_outputs(file_name : string) return output_array_t is
        file expected_file    : text open read_mode is file_name;
        variable outputs      : output_array_t := (others => (others => '0'));
        variable current_line : line;
        variable output_word  : std_logic_vector(SAMPLE_W - 1 downto 0);
        variable read_ok      : boolean;
        variable vector_index : natural := 0;
    begin
        while (not endfile(expected_file)) and (vector_index < TEST_COUNT) loop
            readline(expected_file, current_line);
            hread(current_line, output_word, read_ok);

            assert read_ok
                report "hann_window_4096_tb: invalid expected output at vector " &
                       integer'image(vector_index)
                severity failure;

            outputs(vector_index) := signed(output_word);
            vector_index := vector_index + 1;
        end loop;

        assert vector_index = TEST_COUNT
            report "hann_window_4096_tb: expected-output file has too few lines"
            severity failure;

        return outputs;
    end function load_expected_outputs;

    constant EXPECTED_OUTPUTS : output_array_t :=
        load_expected_outputs("hann_window_4096_tb_expected.mem");

    signal clk              : std_logic := '0';
    signal rst              : std_logic := '1';
    signal sample_in        : signed(SAMPLE_W - 1 downto 0) := (others => '0');
    signal sample_valid_in  : std_logic := '0';
    signal sample_index_in  : unsigned(INDEX_WIDTH - 1 downto 0) := (others => '0');
    signal frame_start_in   : std_logic := '0';
    signal sample_out       : signed(SAMPLE_W - 1 downto 0);
    signal sample_valid_out : std_logic;
    signal sample_index_out : unsigned(INDEX_WIDTH - 1 downto 0);
    signal frame_start_out  : std_logic;

begin

    clk <= not clk after CLK_PERIOD / 2;

    dut : entity work.hann_window_4096
        generic map (
            MEM_FILE => "hann_window.mem"
        )
        port map (
            clk              => clk,
            rst              => rst,
            sample_in        => sample_in,
            sample_valid_in  => sample_valid_in,
            sample_index_in  => sample_index_in,
            frame_start_in   => frame_start_in,
            sample_out       => sample_out,
            sample_valid_out => sample_valid_out,
            sample_index_out => sample_index_out,
            frame_start_out  => frame_start_out
        );

    --------------------------------------------------------------------------
    -- Stimulus and checks.
    --
    -- The DUT has one clock of latency. Each expected output is checked one
    -- clock after the corresponding input vector is driven.
    --------------------------------------------------------------------------
    stim_proc : process
    begin
        wait for 4 * CLK_PERIOD;
        wait until rising_edge(clk);
        rst <= '0';

        for vector_index in 0 to TEST_COUNT - 1 loop
            sample_in       <= TEST_SAMPLES(vector_index);
            sample_index_in <= TEST_INDEXES(vector_index);
            frame_start_in  <= '1' when vector_index = 0 else '0';
            sample_valid_in <= '1';

            wait until rising_edge(clk);
            wait for 1 ns;

            if vector_index > 0 then
                assert sample_valid_out = '1'
                    report "sample_valid_out was not asserted for vector " &
                           integer'image(vector_index - 1)
                    severity failure;

                assert sample_out = EXPECTED_OUTPUTS(vector_index - 1)
                    report "windowed sample mismatch for vector " &
                           integer'image(vector_index - 1)
                    severity failure;

                assert sample_index_out = TEST_INDEXES(vector_index - 1)
                    report "sample_index_out was not aligned for vector " &
                           integer'image(vector_index - 1)
                    severity failure;

                if vector_index = 1 then
                    assert frame_start_out = '1'
                        report "frame_start_out was not asserted for first vector"
                        severity failure;
                else
                    assert frame_start_out = '0'
                        report "frame_start_out was asserted away from first vector"
                        severity failure;
                end if;
            end if;
        end loop;

        sample_valid_in <= '0';
        frame_start_in  <= '0';

        wait until rising_edge(clk);
        wait for 1 ns;

        assert sample_valid_out = '1'
            report "sample_valid_out was not asserted for final vector"
            severity failure;

        assert sample_out = EXPECTED_OUTPUTS(TEST_COUNT - 1)
            report "windowed sample mismatch for final vector"
            severity failure;

        assert sample_index_out = TEST_INDEXES(TEST_COUNT - 1)
            report "sample_index_out was not aligned for final vector"
            severity failure;

        assert frame_start_out = '0'
            report "frame_start_out should not be asserted for final vector"
            severity failure;

        wait until rising_edge(clk);
        wait for 1 ns;

        assert sample_valid_out = '0'
            report "sample_valid_out did not deassert after input valid was removed"
            severity failure;

        report "hann_window_4096_tb completed successfully" severity note;
        finish;
    end process stim_proc;

end architecture sim;
