----------------------------------------------------------------------------------
-- Module Name: adc_sample_rom
--
-- Description:
--   Read-only memory for generated ADC samples.
--
--   This ROM stores 4096 samples, where each sample is a 24-bit two's-complement
--   ADC value produced by the Python sample-generation script. The Python script
--   should create a plain text memory file with one hexadecimal word per line:
--
--     FFFFCC
--     000000
--     0A6CAF
--
--   Each line represents the raw 24-bit ADC word. Negative samples must already
--   be encoded in two's-complement form by Python, typically with:
--
--     mem_word = adc_value & 0xFFFFFF
--
--   The ROM uses a synchronous read so that it maps cleanly to FPGA block RAM.
--   When 'en' is asserted, the sample addressed by 'addr' appears on 'sample'
--   after one rising clock edge.
----------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;
use ieee.std_logic_textio.all;

entity adc_sample_rom is
    generic (
        -- Memory initialization file generated by Python. Vivado simulation and
        -- synthesis must be able to find this file in the project search path.
        MEM_FILE : string := "adc_samples.mem"
    );
    port (
        clk    : in  std_logic;
        en     : in  std_logic;
        addr   : in  unsigned(11 downto 0);
        sample : out signed(23 downto 0)
    );
end entity adc_sample_rom;

architecture rtl of adc_sample_rom is

    --------------------------------------------------------------------------
    -- Memory sizing constants.
    --
    -- A 12-bit address selects one of 4096 samples. Each stored word is kept as
    -- std_logic_vector because the file contains raw hexadecimal bit patterns.
    -- The word is converted to signed only at the registered output.
    --------------------------------------------------------------------------
    constant ROM_DEPTH    : natural := 4096;
    constant SAMPLE_WIDTH : natural := 24;

    --------------------------------------------------------------------------
    -- ROM storage type.
    --
    -- Index 0 corresponds to the first sample in the .mem file, index 1 to the
    -- second sample, and so on through index 4095.
    --------------------------------------------------------------------------
    type rom_t is array (0 to ROM_DEPTH - 1) of std_logic_vector(SAMPLE_WIDTH - 1 downto 0);

    --------------------------------------------------------------------------
    -- ROM initialization function.
    --
    -- This function runs during elaboration/synthesis initialization. It reads
    -- one hexadecimal value per line from MEM_FILE and places that value into
    -- the matching ROM address. Any unread addresses remain zero, which makes a
    -- short simulation file usable while still warning that production sample
    -- data should contain all 4096 words.
    --------------------------------------------------------------------------
    impure function init_rom_from_file(file_name : string) return rom_t is
        file sample_file      : text open read_mode is file_name;
        variable rom_data     : rom_t := (others => (others => '0'));
        variable current_line : line;
        variable sample_word  : std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
        variable read_ok      : boolean;
        variable sample_index : natural := 0;
    begin
        while (not endfile(sample_file)) and (sample_index < ROM_DEPTH) loop
            readline(sample_file, current_line);
            hread(current_line, sample_word, read_ok);

            assert read_ok
                report "adc_sample_rom: invalid hexadecimal sample in " & file_name &
                       " at ROM address " & integer'image(sample_index)
                severity failure;

            rom_data(sample_index) := sample_word;
            sample_index := sample_index + 1;
        end loop;

        assert sample_index = ROM_DEPTH
            report "adc_sample_rom: " & file_name &
                   " contains fewer than 4096 samples; remaining ROM addresses are zero"
            severity warning;

        assert endfile(sample_file)
            report "adc_sample_rom: " & file_name &
                   " contains more than 4096 samples; extra samples are ignored"
            severity warning;

        return rom_data;
    end function init_rom_from_file;

    --------------------------------------------------------------------------
    -- ROM signal.
    --
    -- The block style attribute tells Vivado that this table should be
    -- implemented with block memory resources instead of distributed LUT RAM
    -- when possible.
    --------------------------------------------------------------------------
    signal rom : rom_t := init_rom_from_file(MEM_FILE);

    attribute rom_style : string;
    attribute rom_style of rom : signal is "block";

    --------------------------------------------------------------------------
    -- Registered output sample.
    --
    -- Keeping the output registered matches block RAM timing and gives the
    -- downstream Goertzel datapath a stable, clock-aligned signed sample.
    --------------------------------------------------------------------------
    signal sample_reg : signed(SAMPLE_WIDTH - 1 downto 0) := (others => '0');

begin

    --------------------------------------------------------------------------
    -- Synchronous ROM read.
    --
    -- On each rising edge with en='1', the addressed raw 24-bit word is read
    -- and interpreted as a signed two's-complement ADC sample. When en='0', the
    -- register holds its previous value.
    --------------------------------------------------------------------------
    read_proc : process (clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                sample_reg <= signed(rom(to_integer(addr)));
            end if;
        end if;
    end process read_proc;

    sample <= sample_reg;

end architecture rtl;
