# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
# IP: The module: 'design_1_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
# IP: The module: 'design_1_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Tim/Documents/ECE_615/vivado_projects/final_proj_vivado/final_proj_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
